# Generated by Django 6.0.7 on 2026-08-04 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('country_code', models.CharField(blank=True, help_text='Optional ISO 3166-1 alpha-2 country code.', max_length=2)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive manufacturers remain preserved but are not normally displayed.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_models', to='reference.manufacturer')),
            ],
            options={
                'ordering': ('manufacturer__name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable name, such as Fourth Generation.', max_length=100)),
                ('slug', models.SlugField(max_length=120)),
                ('generation_number', models.PositiveSmallIntegerField(blank=True, help_text='Optional numeric generation sequence, such as 4.', null=True)),
                ('start_year', models.PositiveSmallIntegerField()),
                ('end_year', models.PositiveSmallIntegerField(blank=True, help_text='Leave blank when the generation is still in production.', null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generations', to='reference.vehiclemodel')),
            ],
            options={
                'ordering': ('vehicle_model__manufacturer__name', 'vehicle_model__name', 'start_year'),
            },
        ),
        migrations.CreateModel(
            name='VehicleDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_year', models.PositiveSmallIntegerField()),
                ('trim_name', models.CharField(blank=True, help_text='Manufacturer trim name, such as SR5, Sport Edition, or Limited.', max_length=100)),
                ('engine_name', models.CharField(blank=True, help_text='Human-readable engine description.', max_length=100)),
                ('drivetrain', models.CharField(choices=[('2WD', 'Two-wheel drive'), ('4WD', 'Four-wheel drive'), ('AWD', 'All-wheel drive'), ('UNK', 'Unknown')], default='UNK', max_length=3)),
                ('market', models.CharField(choices=[('US', 'United States'), ('CA', 'Canada'), ('OT', 'Other')], default='US', max_length=2)),
                ('slug', models.SlugField(max_length=180)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_definitions', to='reference.generation')),
            ],
            options={
                'ordering': ('generation__vehicle_model__manufacturer__name', 'generation__vehicle_model__name', 'model_year', 'trim_name', 'engine_name', 'drivetrain'),
                'constraints': [models.UniqueConstraint(fields=('generation', 'slug'), name='reference_unique_vehicle_definition_slug_per_generation')],
            },
        ),
        migrations.AddConstraint(
            model_name='vehiclemodel',
            constraint=models.UniqueConstraint(fields=('manufacturer', 'name'), name='reference_unique_vehicle_model_name_per_manufacturer'),
        ),
        migrations.AddConstraint(
            model_name='vehiclemodel',
            constraint=models.UniqueConstraint(fields=('manufacturer', 'slug'), name='reference_unique_vehicle_model_slug_per_manufacturer'),
        ),
        migrations.AddConstraint(
            model_name='generation',
            constraint=models.UniqueConstraint(fields=('vehicle_model', 'slug'), name='reference_unique_generation_slug_per_vehicle_model'),
        ),
    ]
