# Generated by Django 6.0.7 on 2026-08-15 21:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportExecutionReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('execution_channel', models.CharField(default='cli', max_length=50)),
                ('operator_label', models.CharField(max_length=150)),
                ('manifest_hash', models.CharField(max_length=71)),
                ('candidate_reference', models.CharField(max_length=150)),
                ('planned_action', models.CharField(max_length=30)),
                ('create_basis', models.CharField(blank=True, max_length=30)),
                ('source_id', models.CharField(max_length=100)),
                ('raw_artifact_hash', models.CharField(max_length=71)),
                ('raw_artifact_reference', models.CharField(max_length=255)),
                ('source_identity_type', models.CharField(default='record_id', max_length=50)),
                ('native_identifier', models.CharField(max_length=100)),
                ('resolved_generation_id', models.IntegerField(blank=True, null=True)),
                ('target_slug', models.CharField(max_length=180)),
                ('target_model_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('target_trim_name', models.CharField(blank=True, max_length=100)),
                ('target_engine_name', models.CharField(blank=True, max_length=100)),
                ('target_drivetrain', models.CharField(blank=True, max_length=3)),
                ('target_market', models.CharField(blank=True, max_length=2)),
                ('target_fields_json', models.JSONField(default=dict)),
                ('execution_outcome', models.CharField(max_length=30)),
                ('messages_json', models.JSONField(default=list)),
                ('created_vehicle_definition_pk_snapshot', models.IntegerField(blank=True, null=True)),
                ('created_vehicle_definition_uuid_snapshot', models.CharField(blank=True, max_length=36)),
                ('created_vehicle_definition_slug_snapshot', models.CharField(blank=True, max_length=180)),
                ('existing_vehicle_definition_pk_snapshot', models.IntegerField(blank=True, null=True)),
                ('existing_vehicle_definition_uuid_snapshot', models.CharField(blank=True, max_length=36)),
                ('existing_vehicle_definition_slug_snapshot', models.CharField(blank=True, max_length=180)),
                ('created_vehicle_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creation_receipts', to='reference.vehicledefinition')),
                ('existing_vehicle_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_receipts', to='reference.vehicledefinition')),
            ],
            options={
                'ordering': ('-executed_at',),
            },
        ),
    ]
