# Generated by Django 6.0.7 on 2026-08-15 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0002_importexecutionreceipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='importexecutionreceipt',
            name='adjudication_hash',
            field=models.CharField(blank=True, default='', help_text='SHA-256 digest of verified human adjudication artifact.', max_length=71),
        ),
    ]
