# Generated by Django 6.0.7 on 2026-08-16 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0003_importexecutionreceipt_adjudication_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledefinition',
            name='drivetrain',
            field=models.CharField(choices=[('2WD', '2WD'), ('4WD', '4WD'), ('AWD', 'AWD'), ('UNK', 'Unknown')], default='UNK', max_length=3),
        ),
    ]
