# Generated by Django 6.0.7 on 2026-08-16 04:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0004_alter_vehicledefinition_drivetrain'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanonicalRecordCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('superseded_vehicle_definition_pk_snapshot', models.IntegerField(blank=True, null=True)),
                ('superseded_vehicle_definition_uuid_snapshot', models.CharField(blank=True, max_length=36)),
                ('superseded_vehicle_definition_slug_snapshot', models.CharField(blank=True, max_length=180)),
                ('replacement_vehicle_definition_pk_snapshot', models.IntegerField(blank=True, null=True)),
                ('replacement_vehicle_definition_uuid_snapshot', models.CharField(blank=True, max_length=36)),
                ('replacement_vehicle_definition_slug_snapshot', models.CharField(blank=True, max_length=180)),
                ('correction_reason', models.CharField(default='NORMALIZATION_RULE_CORRECTION', max_length=100)),
                ('operator_label', models.CharField(default='cli', max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('execution_receipt', models.ForeignKey(blank=True, help_text='The execution receipt associated with the replacement promotion.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correction_audit_records', to='reference.importexecutionreceipt')),
                ('replacement_vehicle_definition', models.ForeignKey(blank=True, help_text='The active replacement canonical VehicleDefinition.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_corrections', to='reference.vehicledefinition')),
                ('superseded_vehicle_definition', models.ForeignKey(blank=True, help_text='The historical canonical VehicleDefinition being superseded (is_active=False).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by_corrections', to='reference.vehicledefinition')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
