# Generated by Django 6.0.7 on 2026-08-17 20:15

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference', '0005_canonicalrecordcorrection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicabilityFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='MeasurementDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=120, unique=True)),
                ('category', models.CharField(choices=[('cargo', 'Cargo Area')], default='cargo', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ApplicabilityState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=120)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='states', to='measurements.applicabilityfeature')),
            ],
            options={
                'ordering': ('feature__name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='MeasurementResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unit', models.CharField(choices=[('in', 'Inches'), ('mm', 'Millimeters'), ('cm', 'Centimeters')], default='in', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='measurements.measurementdefinition')),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='measurement_results', to='reference.generation')),
            ],
            options={
                'ordering': ('generation', 'definition__name'),
            },
        ),
        migrations.CreateModel(
            name='MeasurementResultCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='measurements.measurementresult')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='result_conditions', to='measurements.applicabilitystate')),
            ],
            options={
                'ordering': ('result', 'state__feature__name'),
            },
        ),
        migrations.AddConstraint(
            model_name='applicabilitystate',
            constraint=models.UniqueConstraint(fields=('feature', 'name'), name='measurements_unique_state_name_per_feature'),
        ),
        migrations.AddConstraint(
            model_name='applicabilitystate',
            constraint=models.UniqueConstraint(fields=('feature', 'slug'), name='measurements_unique_state_slug_per_feature'),
        ),
        migrations.AddConstraint(
            model_name='measurementresultcondition',
            constraint=models.UniqueConstraint(fields=('result', 'state'), name='measurements_unique_condition_per_result'),
        ),
    ]
