# Generated by Django 6.0.7 on 2026-08-05 01:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('observed_on', models.DateField(blank=True, help_text='Optional date when the real-world observation occurred.', null=True)),
                ('source_notes', models.TextField(blank=True, help_text='Optional notes describing capture context, methodology, or source attribution.')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to=settings.AUTH_USER_MODEL)),
                ('vehicle_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='reference.vehicledefinition')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
